import "@chatmtv/ui/globals.css";
import { CombinedThemeProvider } from "@chatmtv/ui/theme";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainLayout } from "@chatmtv/ui/layout";
import { Toaster } from "sonner";
import { UserSection } from "./user-section";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CombinedThemeProvider>
          <MainLayout userSection={<UserSection />}>{children}</MainLayout>
          <Toaster />
        </CombinedThemeProvider>
      </body>
    </html>
  );
}
